### ISSUE TITLE
Google Docs vs Github, relations and workflows documented?

### ISSUE THREAD

**Issue by ghost** [librecorps/tasks#27]
While skimming the opensource.com [article][10] today, I drilled down two levels deep from the provided links into the Google Docs [reading list][20], and noticed a typo.

I've since done the usual: Forked and cloned the [librecorps/resources repo][25], corrected it in my clone, pushed to my fork, and from my fork issued a [pull request][30] to upstream. Assuming that goes through well enough, that will correct the typo in the repo. (Maybe I should have saved it as an easy bug for [HFOSS][35] but alas sometimes I have to just do the thing.) So far so good.

Along the way of doing that though I noticed a few things that aren't clear to me but that might be documented somewhere if only I can get some pointers and which might help other potential contributors less familiar with LibreCorps day-to-day:

- [ ] What is the relationship between the [resources repo][25] and the Google docs? 

- [ ] How does content flow from one to the other, and in which direction?

- [ ] Since the Google docs versions are the published ones but are not generally editable (I cannot, for instance, edit them from my non-RIT Google account), how might someone who is less familiar than me with our idiosyncratic use of `tasks` repos meant to channel their contributions? Any chance we can eventually replace each of the Google docs with some short text redirecting to their counterparts on the web site? 

- [ ] I noticed that the [config.toml][40] file makes reference to  [https://librecorps.github.io/resources][50] which is fine. but the base URL [(https://librecorps.github.io/)][60] is 404, which I found disorienting.
 
[10]: https://opensource.com/article/19/12/humanitarian-startups-open-source
[20]: https://docs.google.com/document/d/1A6UbSrJ-uhhGA5XYfKEEyYvI-PByf4am7u9XwfDsbh0
[25]: https://github.com/librecorps/resources
[30]: https://github.com/librecorps/resources/pull/7
[35]: https://github.com/ritjoe/hfoss
[40]: https://github.com/librecorps/resources/blob/master/config.toml
[50]: https://librecorps.github.io/resources
[60]: https://librecorps.github.io

**Comment by Nolski** [comment]
This is a great question. So, we originally started developing all of our documents using Google Docs due to its ability to support real-time collaboration. As an initial attempt to publish these in a way that's a bit more friendly to consume online (and separate from Google docs) we made an [initial attempt](https://github.com/librecorps/resources/pull/5) at throwing most (but not all) of our resources through pandoc and publish them on a static website in markdown.

We don't yet have a good workflow yet for keeping these documents in sync. In general, when we have shared our resources, we have linked to the google docs. In terms of fostering further collaboration among them, that's been a significant problem that we haven't yet solved. :(

**Comment by Nolski** [comment]
With regard to the config, I suspect this is just a bug.

**Comment by justwheel** [comment]
_Included in 2020-03-24 issue triage and cleanup._

---

This is something I want to address, but @Nolski has an issue open for a similar topic in #12. I'm going to use that issue as a central place to discuss how our content on closed platforms makes its way into more open content.

Closing as duplicate. :clapper:
